// frontend/src/components/AboutPage.vue
<template>
  <div>
    <h1>About Page</h1>
    <div v-if="userInfo && userInfo.isAuthenticated">
      <p v-if="userInfo.user.username">Welcome, {{ userInfo.user.username }}!</p>
      <p v-else>Welcome, {{ userInfo.user.first_name }} {{ userInfo.user.last_name }}!</p>
      <button @click="handleLogout">Sign Out</button>
    </div>
    <div v-else>
      <p>You are not logged in.</p>
      <a href="http://localhost:8082/microsoft-login/">Login with Microsoft</a>
    </div>
  </div>
</template>

<script>
import apiService from '../services/apiService';

export default {
  data() {
    return {
      userInfo: null, // Start with null to handle the loading state
    };
  },
  created() {
    this.fetchUserInfo();
  },
  methods: {
    async fetchUserInfo() {
      try {
        const response = await apiService.getUserInfo();
        this.userInfo = response.data;
      } catch (error) {
        console.error('Error fetching user info:', error);
        this.userInfo = { isAuthenticated: false }; // Handle case where fetching fails
      }
    },
    async handleLogout() {
      try {
        const response = await apiService.logout();
        if (response.data.success) {
          this.userInfo = null; // Clear user info after logout
          this.$router.push('/'); // Redirect to the homepage after logout
        } else {
          console.error('Logout failed:', response.data.message);
        }
      } catch (error) {
        console.error('Error logging out:', error);
      }
    },
  },
};
</script>

// vite-project/src/pages/AboutPage.tsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import apiService from '../services/apiService';

const AboutPage: React.FC = () => {
  const navigate = useNavigate();
  const [userInfo, setUserInfo] = useState({
    username: sessionStorage.getItem('username') || '',
    firstName: sessionStorage.getItem('firstName') || '',
    lastName: sessionStorage.getItem('lastName') || ''
  });

  // Check if user information exists to determine logged in state
  const isAuthenticated = Boolean(userInfo.username);

  useEffect(() => {
    // If no username is found in session storage, fetch user info
    if (!userInfo.username) {
      const fetchUserInfo = async () => {
        try {
          const response = await apiService.getUserInfo();
          if (response.data.user) {
            setUserInfo({
              username: response.data.user.username || '',
              firstName: response.data.user.first_name || '',
              lastName: response.data.user.last_name || ''
            });
          }
        } catch (error) {
          console.error('Error fetching user info:', error);
        }
      };
      fetchUserInfo();
    }
  }, [userInfo.username]);

  // Handle user logout
  const handleLogout = async () => {
    try {
      const response = await apiService.logout();
      if (response.data.success) {
        sessionStorage.clear(); // Clear all session storage
        setUserInfo({ username: '', firstName: '', lastName: '' }); // Reset user info state
        navigate('/login'); // Redirect to the login page
      } else {
        console.error('Logout failed:', response.data.message);
      }
    } catch (error) {
      console.error('Error logging out:', error);
    }
  };

  return (
    <div>
      <h1>About Page</h1>
      {isAuthenticated ? (
        <div>
          <p>Welcome, {userInfo.username || `${userInfo.firstName} ${userInfo.lastName}`}!</p>
          <button onClick={handleLogout}>Log Out</button>
        </div>
      ) : (
        <p>You are not logged in. Please <a href="/login">log in</a>.</p>
      )}
    </div>
  );
};

export default AboutPage;
