// frontend/src/components/AboutPage.vue
<template>
  <div>
    <h1>About Page</h1>
    <div v-if="userInfo && userInfo.isAuthenticated">
      <p v-if="userInfo.user.username">Welcome, {{ userInfo.user.username }}!</p>
      <p v-else>Welcome, {{ userInfo.user.first_name }} {{ userInfo.user.last_name }}!</p>
      <button @click="handleLogout">Sign Out</button>
    </div>
    <div v-else>
      <p>You are not logged in.</p>
      <a href="http://localhost:8082/microsoft-login/">Login with Microsoft</a>
    </div>
  </div>
</template>

<script>
import apiService from '../services/apiService';

export default {
  data() {
    return {
      userInfo: null, // Start with null to handle the loading state
    };
  },
  created() {
    this.fetchUserInfo();
  },
  methods: {
    async fetchUserInfo() {
      try {
        const response = await apiService.getUserInfo();
        this.userInfo = response.data;
      } catch (error) {
        console.error('Error fetching user info:', error);
        this.userInfo = { isAuthenticated: false }; // Handle case where fetching fails
      }
    },
    async handleLogout() {
      try {
        const response = await apiService.logout();
        if (response.data.success) {
          this.userInfo = null; // Clear user info after logout
          this.$router.push('/'); // Redirect to the homepage after logout
        } else {
          console.error('Logout failed:', response.data.message);
        }
      } catch (error) {
        console.error('Error logging out:', error);
      }
    },
  },
};
</script>

// vite-project/src/components/AboutPage.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import apiService, { UserInfo } from '../services/apiService';

const AboutPage: React.FC = () => {
  const [userInfo, setUserInfo] = useState<{ isAuthenticated: boolean; user: UserInfo } | null>(null);
  const navigate = useNavigate();

  // Fetch user info on component mount
  useEffect(() => {
    const fetchUserInfo = async () => {
      try {
        const response = await apiService.getUserInfo();
        setUserInfo(response.data); // Set user info from API response
      } catch (error) {
        console.error('Error fetching user info:', error);
        setUserInfo({ isAuthenticated: false, user: {} as UserInfo }); // Set as unauthenticated if an error occurs
      }
    };
    fetchUserInfo();
  }, []);

  // Handle user logout
  const handleLogout = async () => {
    try {
      const response = await apiService.logout();
      if (response.data.success) {
        setUserInfo(null); // Clear user info after logout
        navigate('/'); // Redirect to homepage after logout
      } else {
        console.error('Logout failed:', response.data.message); // Use response.data.message safely now
      }
    } catch (error) {
      console.error('Error logging out:', error);
    }
  };

  return (
    <div>
      <h1>About Page</h1>
      {userInfo && userInfo.isAuthenticated ? (
        <div>
          {userInfo.user.username ? (
            <p>Welcome, {userInfo.user.username}!</p>
          ) : (
            <p>
              Welcome, {userInfo.user.first_name} {userInfo.user.last_name}!
            </p>
          )}
          <button onClick={handleLogout}>Sign Out</button>
        </div>
      ) : (
        <div>
          <p>You are not logged in.</p>
          <a href="http://localhost:8082/login">Login with Microsoft</a>
        </div>
      )}
    </div>
  );
};

export default AboutPage;
